### ISSUE TITLE
Flutter 3.13.9 Old Kotlin version breaks build process

### ISSUE THREAD

**Issue by robinduerhager** [easazade/android-long-task#15]
Hi,

i received the following error in my Flutter 3.13.9 project:
```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':android_long_task' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
```

I fixed the Error by adjusting the Kotlin Version. I will submit a PR :).
In the meantime, if anyone suffers from this error, you might be able to get around this by using the following in your pubspec.yaml file:

```yaml
  android_long_task:
    git:
      url: 'https://github.com/robinduerhager/android_long_task.git'
      ref: '3f90808ff72e6bead9b77de4655f9439c4b82482'
```
